'use server';

import { createClient } from '@/utils/supabase/server';
import { revalidatePath } from 'next/cache';

export async function createTable(formData: FormData) {
    const supabase = await createClient();
    const name = formData.get('name') as string;

    if (!name) return { error: 'Name is required' };

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { error: 'Unauthorized' };

    // Token is generated by default uuid function in DB, but we can also generate here to be explicit/safe 
    // or if we want a different format. 
    // The schema says "id uuid default uuid_generate_v4()", "token text unique".
    // Let's generate a random secure token here or use crypto.
    // Actually, using UUID for token is fine.
    const token = crypto.randomUUID();
    const baseUrl = (process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000').replace(/\/$/, '');
    const qr_code_url = `${baseUrl}/menu/${token}`;

    const { error } = await supabase.from('tables').insert({
        name,
        token,
        qr_code_url,
        user_id: user.id
    });

    if (error) {
        console.error('Error creating table:', error);
        return { error: `Failed to create table: ${error.message}` };
    }

    revalidatePath('/admin/tables');
    return { success: true };
}

export async function deleteTable(id: string) {
    const supabase = await createClient();

    // 1. Delete orders associated with this table first (Cascading delete manually)
    const { error: ordersError } = await supabase.from('orders').delete().eq('table_id', id);
    if (ordersError) {
        console.error('Error deleting table orders:', ordersError);
        return { error: `Failed to cleanup table orders: ${ordersError.message}` };
    }

    // 2. Delete the table
    const { error } = await supabase.from('tables').delete().eq('id', id);

    if (error) {
        return { error: `Failed to delete table: ${error.message}` };
    }

    revalidatePath('/admin/tables');
    return { success: true };
}
